@startmindmap Spring Design Pattern
<style>
mindmapDiagram {
    :depth(0) {
        BackGroundColor red
    }
    node {
        BackgroundColor PowDerBlue
    }
    :depth(1) {
        BackGroundColor DarkSlateBlue
    }
    :depth(2) {
        BackGroundColor RoyalBlue
    }
}
</style>

title  Spring设计模式
+[#SlateGray] Spring设计模式
++ 传统GoF 23
-- Spring专属设计模式
---[#SteelBlue]  前缀模式
---- Enable模式
---- Configurable模式
---[#CornflowerBlue] 后缀模式
---- 处理模式
-----_ Processor
-----_ Resolver
-----_ Handler
---- 意识模式
-----_ Aware
---- 配置器模式
-----_ Configuror
---- 选择器模式
-----_ context.annotation

@endmindmap
